services:
  - type: web
    name: voxcampus-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: voxcampus-algo
    runtime: python
    rootDir: algo-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
